const PERMISSIONS = {
  ADMIN_DASHBOARD_ACCESS: 'admin.dashboard.access',

  ADMIN_INBOX_VIEW: 'admin.inbox.view',
  ADMIN_ORDERS_VIEW: 'admin.orders.view',
  ADMIN_ORDERS_MANAGE: 'admin.orders.manage',
  ADMIN_REFUNDS_MANAGE: 'admin.refunds.manage',
  ADMIN_SUPPORT_MANAGE: 'admin.support.manage',

  ADMIN_USERS_VIEW: 'admin.users.view',
  ADMIN_USERS_MANAGE_ROLES: 'admin.users.manage_roles',
  ADMIN_USERS_MANAGE_PERMISSIONS: 'admin.users.manage_permissions',
  ADMIN_USERS_DELETE: 'admin.users.delete',

  ADMIN_DRIVERS_MANAGE: 'admin.drivers.manage',
  ADMIN_DELIVERY_COVERAGE_MANAGE: 'admin.delivery_coverage.manage',
  ADMIN_CASHIERS_MANAGE: 'admin.cashiers.manage',

  ADMIN_PRODUCTS_VIEW: 'admin.products.view',
  ADMIN_PRODUCTS_MANAGE: 'admin.products.manage',
  ADMIN_PRODUCTS_ACCESS: 'admin.products.access',
  ADMIN_STOCKS_MANAGE: 'admin.stocks.manage',
  ADMIN_STOCKS_ACCESS: 'admin.stocks.access',
  ADMIN_PROMOTIONS_MANAGE: 'admin.promotions.manage',
  ADMIN_PROMOTIONS_ACCESS: 'admin.promotions.access',

  ADMIN_SALES_VIEW: 'admin.sales.view',
  ADMIN_REPORTS_VIEW: 'admin.reports.view',

  ADMIN_EMERGENCY_SALES_MANAGE: 'admin.emergency_sales.manage',
  ADMIN_EMERGENCY_SALES_ACCESS: 'admin.emergency_sales.access',
  ADMIN_EMERGENCY_REPORTS_VIEW: 'admin.emergency_reports.view',
  ADMIN_POS_MANAGEMENT: 'admin.pos.management',
  ADMIN_POS_SYNC_MANAGE: 'admin.pos_sync.manage',

  ADMIN_QUOTATIONS_MANAGE: 'admin.quotations.manage',

  ADMIN_USERS_MANAGEMENT_ACCESS: 'admin.users_management.access',

  ADMIN_BUSINESS_OPERATIONS_VIEW: 'admin.business_operations.view',
  ADMIN_BUSINESS_OPERATIONS_ACCESS: 'admin.business_operations.access',
  ADMIN_GOODS_INTAKE_MANAGE: 'admin.goods_intake.manage',
  ADMIN_EMPLOYEES_MANAGE: 'admin.employees.manage',
  ADMIN_PAYROLL_MANAGE: 'admin.payroll.manage',
  ADMIN_EXPENSES_MANAGE: 'admin.expenses.manage',
  ADMIN_IMPORT_EXPORT_MANAGE: 'admin.import_export.manage',

  BO_SALES_REPORTS_VIEW: 'admin.business_operations.sales_reports.view',
  BO_SUPPLIERS_VIEW: 'admin.business_operations.suppliers.view',
  BO_GOODS_INTAKE_VIEW: 'admin.business_operations.goods_intake.view',
  BO_PURCHASE_ORDERS_VIEW: 'admin.business_operations.purchase_orders.view',
  BO_PURCHASE_ORDERS_CREATE: 'admin.business_operations.purchase_orders.create',
  BO_PURCHASE_ORDERS_EDIT: 'admin.business_operations.purchase_orders.edit',
  BO_PURCHASE_ORDERS_DELETE: 'admin.business_operations.purchase_orders.delete',
  BO_PURCHASE_ORDERS_EXPORT: 'admin.business_operations.purchase_orders.export',
  BO_EXPENSES_VIEW: 'admin.business_operations.expenses.view',
  BO_MONTHLY_SUMMARY_VIEW: 'admin.business_operations.monthly_summary.view',
  BO_EMPLOYEES_VIEW: 'admin.business_operations.employees.view',
  BO_PAYROLL_VIEW: 'admin.business_operations.payroll.view',
  BO_REPORT_HISTORY_VIEW: 'admin.business_operations.report_history.view',
  BO_SALES_BALANCING_VIEW: 'admin.business_operations.sales_balancing.view',
  BO_ANALYTICS_VIEW: 'admin.business_operations.analytics.view',
  BO_INVENTORY_ACTIVITY_VIEW: 'admin.business_operations.inventory_activity.view',
  BO_ACTIONS_VIEW: 'admin.business_operations.actions.view',

  BO_MONTHLY_SUMMARY_OVERVIEW_CARDS_VIEW: 'admin.business_operations.monthly_summary.overview_cards.view',
  BO_MONTHLY_SUMMARY_SALES_OVERVIEW_VIEW: 'admin.business_operations.monthly_summary.sales_overview.view',
  BO_MONTHLY_SUMMARY_EXPENSES_OVERVIEW_VIEW: 'admin.business_operations.monthly_summary.expenses_overview.view',
  BO_MONTHLY_SUMMARY_PAYROLL_OVERVIEW_VIEW: 'admin.business_operations.monthly_summary.payroll_overview.view',
  BO_MONTHLY_SUMMARY_SUPPLIERS_OVERVIEW_VIEW: 'admin.business_operations.monthly_summary.suppliers_overview.view',
  BO_MONTHLY_SUMMARY_NET_OVERVIEW_VIEW: 'admin.business_operations.monthly_summary.net_overview.view',
  BO_GOODS_INTAKE_FORM_VIEW: 'admin.business_operations.goods_intake.form.view',
  BO_GOODS_INTAKE_HISTORY_VIEW: 'admin.business_operations.goods_intake.history.view',
  BO_SALES_REPORTS_SUMMARY_VIEW: 'admin.business_operations.sales_reports.summary.view',
  BO_SALES_REPORTS_SALES_BY_VIEW: 'admin.business_operations.sales_reports.sales_by.view',

  BO_GOODS_INTAKE_CREATE: 'admin.business_operations.goods_intake.create',
  BO_GOODS_INTAKE_EDIT: 'admin.business_operations.goods_intake.edit',
  BO_GOODS_INTAKE_DELETE: 'admin.business_operations.goods_intake.delete',
  BO_GOODS_INTAKE_EXPORT: 'admin.business_operations.goods_intake.export',
  BO_SALES_REPORTS_EXPORT: 'admin.business_operations.sales_reports.export',
  BO_SALES_REPORTS_IMPORT: 'admin.business_operations.sales_reports.import',
  BO_SALES_REPORTS_FULL_WORKBOOK_EXPORT: 'admin.business_operations.sales_reports.full_workbook.export',
  BO_SALES_REPORTS_FULL_WORKBOOK_IMPORT: 'admin.business_operations.sales_reports.full_workbook.import',
  BO_ACTIONS_WIPE_DATA: 'admin.business_operations.actions.wipe_data',

  ADMIN_SYSTEM_MANAGE: 'admin.system.manage',
  ADMIN_SECURITY_MANAGE: 'admin.security.manage',
};

const ALL_PERMISSION_KEYS = Object.freeze(Object.values(PERMISSIONS));

const ROLE_DEFAULT_PERMISSIONS = Object.freeze({
  super_admin: ALL_PERMISSION_KEYS,
  admin: ALL_PERMISSION_KEYS,
  driver: [],
  cashier: [],
  user: [],
});

const PERMISSION_GROUPS = Object.freeze([
  {
    id: 'core',
    label: 'Core Access',
    permissions: [
      { key: PERMISSIONS.ADMIN_DASHBOARD_ACCESS, label: 'Admin dashboard access' },
    ],
  },
  {
    id: 'online',
    label: 'Online Store Operations',
    permissions: [
      { key: PERMISSIONS.ADMIN_INBOX_VIEW, label: 'Inbox' },
      { key: PERMISSIONS.ADMIN_ORDERS_VIEW, label: 'Orders' },
      { key: PERMISSIONS.ADMIN_ORDERS_MANAGE, label: 'Manage orders' },
      { key: PERMISSIONS.ADMIN_REFUNDS_MANAGE, label: 'Manage refunds' },
      { key: PERMISSIONS.ADMIN_SUPPORT_MANAGE, label: 'Support tickets' },
      { key: PERMISSIONS.ADMIN_USERS_VIEW, label: 'View users' },
      { key: PERMISSIONS.ADMIN_USERS_MANAGEMENT_ACCESS, label: 'Users management panel access' },
      { key: PERMISSIONS.ADMIN_USERS_MANAGE_ROLES, label: 'Manage user roles' },
      { key: PERMISSIONS.ADMIN_USERS_MANAGE_PERMISSIONS, label: 'Manage user permissions' },
      { key: PERMISSIONS.ADMIN_USERS_DELETE, label: 'Delete users' },
      { key: PERMISSIONS.ADMIN_DRIVERS_MANAGE, label: 'Manage drivers' },
      { key: PERMISSIONS.ADMIN_DELIVERY_COVERAGE_MANAGE, label: 'Manage delivery coverage' },
      { key: PERMISSIONS.ADMIN_SALES_VIEW, label: 'Sales analytics' },
    ],
  },
  {
    id: 'catalog',
    label: 'Shared Catalog',
    permissions: [
      { key: PERMISSIONS.ADMIN_PRODUCTS_VIEW, label: 'View products' },
      { key: PERMISSIONS.ADMIN_PRODUCTS_ACCESS, label: 'Products panel access' },
      { key: PERMISSIONS.ADMIN_PRODUCTS_MANAGE, label: 'Manage products' },
      { key: PERMISSIONS.ADMIN_STOCKS_ACCESS, label: 'Stocks panel access' },
      { key: PERMISSIONS.ADMIN_STOCKS_MANAGE, label: 'Manage stock overrides' },
      { key: PERMISSIONS.ADMIN_PROMOTIONS_ACCESS, label: 'Promotions panel access' },
      { key: PERMISSIONS.ADMIN_PROMOTIONS_MANAGE, label: 'Manage promotions' },
      { key: PERMISSIONS.ADMIN_REPORTS_VIEW, label: 'View reports' },
    ],
  },
  {
    id: 'pos',
    label: 'POS and Emergency',
    permissions: [
      { key: PERMISSIONS.ADMIN_EMERGENCY_SALES_MANAGE, label: 'Emergency sales' },
      { key: PERMISSIONS.ADMIN_EMERGENCY_SALES_ACCESS, label: 'Emergency sales panel access' },
      { key: PERMISSIONS.ADMIN_EMERGENCY_REPORTS_VIEW, label: 'Emergency reports' },
      { key: PERMISSIONS.ADMIN_POS_MANAGEMENT, label: 'POS product management' },
      { key: PERMISSIONS.ADMIN_POS_SYNC_MANAGE, label: 'POS sync monitor and controls' },
      { key: PERMISSIONS.ADMIN_CASHIERS_MANAGE, label: 'Manage emergency cashiers' },
    ],
  },
  {
    id: 'business',
    label: 'Business Operations',
    permissions: [
      { key: PERMISSIONS.ADMIN_QUOTATIONS_MANAGE, label: 'Quotations' },
      { key: PERMISSIONS.ADMIN_BUSINESS_OPERATIONS_VIEW, label: 'Business operations dashboard' },
      { key: PERMISSIONS.ADMIN_BUSINESS_OPERATIONS_ACCESS, label: 'Business operations panel access', level: 'panel' },
      { key: PERMISSIONS.BO_SALES_REPORTS_VIEW, label: 'Sales Reports tab', level: 'tab', parentKey: PERMISSIONS.ADMIN_BUSINESS_OPERATIONS_ACCESS },
      { key: PERMISSIONS.BO_SALES_REPORTS_SUMMARY_VIEW, label: 'Sales Reports summary section', level: 'section', parentKey: PERMISSIONS.BO_SALES_REPORTS_VIEW },
      { key: PERMISSIONS.BO_SALES_REPORTS_SALES_BY_VIEW, label: 'Sales Reports sales-by section', level: 'section', parentKey: PERMISSIONS.BO_SALES_REPORTS_VIEW },
      { key: PERMISSIONS.BO_SALES_REPORTS_EXPORT, label: 'Sales Reports export actions', level: 'action', parentKey: PERMISSIONS.BO_SALES_REPORTS_VIEW },
      { key: PERMISSIONS.BO_SALES_REPORTS_IMPORT, label: 'Sales Reports import actions', level: 'action', parentKey: PERMISSIONS.BO_SALES_REPORTS_VIEW },
      { key: PERMISSIONS.BO_SALES_REPORTS_FULL_WORKBOOK_EXPORT, label: 'Sales Reports full workbook export', level: 'action', parentKey: PERMISSIONS.BO_SALES_REPORTS_VIEW },
      { key: PERMISSIONS.BO_SALES_REPORTS_FULL_WORKBOOK_IMPORT, label: 'Sales Reports full workbook import', level: 'action', parentKey: PERMISSIONS.BO_SALES_REPORTS_VIEW },
      { key: PERMISSIONS.BO_SUPPLIERS_VIEW, label: 'Suppliers tab', level: 'tab', parentKey: PERMISSIONS.ADMIN_BUSINESS_OPERATIONS_ACCESS },
      { key: PERMISSIONS.BO_GOODS_INTAKE_VIEW, label: 'Goods Intake tab', level: 'tab', parentKey: PERMISSIONS.ADMIN_BUSINESS_OPERATIONS_ACCESS },
      { key: PERMISSIONS.BO_GOODS_INTAKE_FORM_VIEW, label: 'Goods Intake form section', level: 'section', parentKey: PERMISSIONS.BO_GOODS_INTAKE_VIEW },
      { key: PERMISSIONS.BO_GOODS_INTAKE_HISTORY_VIEW, label: 'Goods Intake history section', level: 'section', parentKey: PERMISSIONS.BO_GOODS_INTAKE_VIEW },
      { key: PERMISSIONS.BO_GOODS_INTAKE_CREATE, label: 'Goods Intake create', level: 'action', parentKey: PERMISSIONS.BO_GOODS_INTAKE_VIEW },
      { key: PERMISSIONS.BO_GOODS_INTAKE_EDIT, label: 'Goods Intake edit', level: 'action', parentKey: PERMISSIONS.BO_GOODS_INTAKE_VIEW },
      { key: PERMISSIONS.BO_GOODS_INTAKE_DELETE, label: 'Goods Intake delete', level: 'action', parentKey: PERMISSIONS.BO_GOODS_INTAKE_VIEW },
      { key: PERMISSIONS.BO_GOODS_INTAKE_EXPORT, label: 'Goods Intake export', level: 'action', parentKey: PERMISSIONS.BO_GOODS_INTAKE_VIEW },
      { key: PERMISSIONS.BO_PURCHASE_ORDERS_VIEW, label: 'Purchase Orders tab', level: 'tab', parentKey: PERMISSIONS.ADMIN_BUSINESS_OPERATIONS_ACCESS },
      { key: PERMISSIONS.BO_PURCHASE_ORDERS_CREATE, label: 'Purchase Orders create', level: 'action', parentKey: PERMISSIONS.BO_PURCHASE_ORDERS_VIEW },
      { key: PERMISSIONS.BO_PURCHASE_ORDERS_EDIT, label: 'Purchase Orders edit', level: 'action', parentKey: PERMISSIONS.BO_PURCHASE_ORDERS_VIEW },
      { key: PERMISSIONS.BO_PURCHASE_ORDERS_DELETE, label: 'Purchase Orders delete', level: 'action', parentKey: PERMISSIONS.BO_PURCHASE_ORDERS_VIEW },
      { key: PERMISSIONS.BO_PURCHASE_ORDERS_EXPORT, label: 'Purchase Orders export', level: 'action', parentKey: PERMISSIONS.BO_PURCHASE_ORDERS_VIEW },
      { key: PERMISSIONS.BO_EXPENSES_VIEW, label: 'Expenses tab', level: 'tab', parentKey: PERMISSIONS.ADMIN_BUSINESS_OPERATIONS_ACCESS },
      { key: PERMISSIONS.BO_MONTHLY_SUMMARY_VIEW, label: 'Monthly Summary tab', level: 'tab', parentKey: PERMISSIONS.ADMIN_BUSINESS_OPERATIONS_ACCESS },
      { key: PERMISSIONS.BO_MONTHLY_SUMMARY_OVERVIEW_CARDS_VIEW, label: 'Monthly Summary overview cards', level: 'section', parentKey: PERMISSIONS.BO_MONTHLY_SUMMARY_VIEW },
      { key: PERMISSIONS.BO_MONTHLY_SUMMARY_SALES_OVERVIEW_VIEW, label: 'Monthly Summary sales overview', level: 'section', parentKey: PERMISSIONS.BO_MONTHLY_SUMMARY_VIEW },
      { key: PERMISSIONS.BO_MONTHLY_SUMMARY_EXPENSES_OVERVIEW_VIEW, label: 'Monthly Summary expenses overview', level: 'section', parentKey: PERMISSIONS.BO_MONTHLY_SUMMARY_VIEW },
      { key: PERMISSIONS.BO_MONTHLY_SUMMARY_PAYROLL_OVERVIEW_VIEW, label: 'Monthly Summary payroll overview', level: 'section', parentKey: PERMISSIONS.BO_MONTHLY_SUMMARY_VIEW },
      { key: PERMISSIONS.BO_MONTHLY_SUMMARY_SUPPLIERS_OVERVIEW_VIEW, label: 'Monthly Summary supplier overview', level: 'section', parentKey: PERMISSIONS.BO_MONTHLY_SUMMARY_VIEW },
      { key: PERMISSIONS.BO_MONTHLY_SUMMARY_NET_OVERVIEW_VIEW, label: 'Monthly Summary net overview', level: 'section', parentKey: PERMISSIONS.BO_MONTHLY_SUMMARY_VIEW },
      { key: PERMISSIONS.BO_EMPLOYEES_VIEW, label: 'Employees tab', level: 'tab', parentKey: PERMISSIONS.ADMIN_BUSINESS_OPERATIONS_ACCESS },
      { key: PERMISSIONS.BO_PAYROLL_VIEW, label: 'Payroll tab', level: 'tab', parentKey: PERMISSIONS.ADMIN_BUSINESS_OPERATIONS_ACCESS },
      { key: PERMISSIONS.BO_REPORT_HISTORY_VIEW, label: 'Report History tab', level: 'tab', parentKey: PERMISSIONS.ADMIN_BUSINESS_OPERATIONS_ACCESS },
      { key: PERMISSIONS.BO_SALES_BALANCING_VIEW, label: 'Sales Balancing tab', level: 'tab', parentKey: PERMISSIONS.ADMIN_BUSINESS_OPERATIONS_ACCESS },
      { key: PERMISSIONS.BO_ANALYTICS_VIEW, label: 'Analytics tab', level: 'tab', parentKey: PERMISSIONS.ADMIN_BUSINESS_OPERATIONS_ACCESS },
      { key: PERMISSIONS.BO_INVENTORY_ACTIVITY_VIEW, label: 'Inventory Activity tab', level: 'tab', parentKey: PERMISSIONS.ADMIN_BUSINESS_OPERATIONS_ACCESS },
      { key: PERMISSIONS.BO_ACTIONS_VIEW, label: 'Actions tab', level: 'tab', parentKey: PERMISSIONS.ADMIN_BUSINESS_OPERATIONS_ACCESS },
      { key: PERMISSIONS.BO_ACTIONS_WIPE_DATA, label: 'Wipe business data action', level: 'action', parentKey: PERMISSIONS.BO_ACTIONS_VIEW },
      { key: PERMISSIONS.ADMIN_GOODS_INTAKE_MANAGE, label: 'Goods intake' },
      { key: PERMISSIONS.ADMIN_EMPLOYEES_MANAGE, label: 'Employees' },
      { key: PERMISSIONS.ADMIN_PAYROLL_MANAGE, label: 'Payroll' },
      { key: PERMISSIONS.ADMIN_EXPENSES_MANAGE, label: 'Expenses' },
      { key: PERMISSIONS.ADMIN_IMPORT_EXPORT_MANAGE, label: 'Import and export' },
    ],
  },
  {
    id: 'administration',
    label: 'Administration',
    permissions: [
      { key: PERMISSIONS.ADMIN_SYSTEM_MANAGE, label: 'System settings' },
      { key: PERMISSIONS.ADMIN_SECURITY_MANAGE, label: 'Security settings' },
    ],
  },
]);

const isValidPermissionKey = (key) => ALL_PERMISSION_KEYS.includes(key);

module.exports = {
  PERMISSIONS,
  ALL_PERMISSION_KEYS,
  ROLE_DEFAULT_PERMISSIONS,
  PERMISSION_GROUPS,
  isValidPermissionKey,
};
