-- AlterTable
ALTER TABLE "Order"
ADD COLUMN "vat_enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN "vat_rate_percent" DOUBLE PRECISION NOT NULL DEFAULT 16.5,
ADD COLUMN "vat_amount" DOUBLE PRECISION NOT NULL DEFAULT 0;